<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFaWnFx4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFaWnFx4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFaWnFx4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFaWnFx4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFaWnFx4\App_KernelDevDebugContainer([
    'container.build_hash' => 'FaWnFx4',
    'container.build_id' => '87b67be4',
    'container.build_time' => 1712921628,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFaWnFx4');
